### ISSUE TITLE
Recent error "Didn't find class "android.webkit.SafeBrowsingResponse"

### ISSUE THREAD

**Issue by Umar3x** [xamarin/GooglePlayServicesComponents#105]
### Xamarin.Android Version (eg: 6.0):
Xamarin Forms 2.5

### Operating System & Version (eg: Mac OSX 10.11):
Android 7.0

### Google Play Services Version (eg: 8.4.0):
Google play services.ads 60.1142.1

### Describe your Issue:

When landing on app, where the ad is displayed, got this error since yesterday, only on Android 7.0, working on 5.0, 6.0 and 8.0/8.1.
 "Didn't find class "android.webkit.SafeBrowsingResponse"

### Include any relevant Exception Stack traces, build logs, adb logs:

```
04-12 17:02:41.650 I/art     (25961): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.db>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/RenderProcessGoneDetail;
04-12 17:02:41.650 I/art     (25961):   at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (WebViewChromium.java:42)
04-12 17:02:41.650 I/art     (25961):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:636)
04-12 17:02:41.650 I/art     (25961):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:572)
04-12 17:02:41.650 I/art     (25961):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:555)
04-12 17:02:41.650 I/art     (25961):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:542)
04-12 17:02:41.650 I/art     (25961):   at void android.webkit.WebView.<init>(android.content.Context) (WebView.java:532)
04-12 17:02:41.650 I/art     (25961):   at void com.google.android.gms.ads.internal.webview.u.<init>(com.google.android.gms.ads.internal.webview.at, com.google.android.gms.ads.internal.webview.av, java.lang.String, boolean, gh, com.google.android.gms.ads.internal.util.client.m, com.google.android.gms.ads.internal.csi.l, com.google.android.gms.ads.internal.bn, com.google.android.gms.ads.internal.w, com.google.android.gms.ads.internal.clearcut.a) (:com.google.android.gms.dynamite_dynamitemodulesa@12521023@12.5.21 (040408-189987672):1)
04-12 17:02:41.650 I/art     (25961):   at java.lang.Object com.google.android.gms.ads.internal.webview.q.call() ((null):5)
04-12 17:02:41.650 I/art     (25961):   at java.lang.Object com.google.android.gms.ads.internal.util.br.a(java.util.concurrent.Callable) (:com.google.android.gms.dynamite_dynamitemodulesa@12521023@12.5.21 (040408-189987672):23)
04-12 17:02:41.650 I/art     (25961):   at com.google.android.gms.ads.internal.webview.i com.google.android.gms.ads.internal.webview.o.a(android.content.Context, com.google.android.gms.ads.internal.webview.av, java.lang.String, boolean, boolean, gh, com.google.android.gms.ads.internal.util.client.m, com.google.android.gms.ads.internal.csi.l, com.google.android.gms.ads.internal.bn, com.google.android.gms.ads.internal.w, com.google.android.gms.ads.internal.clearcut.a) (:com.google.android.gms.dynamite_dynamitemodulesa@12521023@12.5.21 (040408-189987672):8)
04-12 17:02:41.650 I/art     (25961):   at com.google.android.gms.ads.internal.webview.i com.google.android.gms.ads.nonagon.ad.webview.a.a(com.google.android.gms.ads.internal.client.k) (:com.google.android.gms.dynamite_dynamitemodulesa@12521023@12.5.21 (040408-189987672):11)
04-12 17:02:41.650 I/art     (25961):   at com.google.android.gms.ads.internal.util.future.w com.google.android.gms.ads.nonagon.render.f.a(java.lang.Object) ((null):4)
04-12 17:02:41.650 I/art     (25961):   at void com.google.android.gms.ads.internal.util.future.j.run() ((null):3)
04-12 17:02:41.650 I/art     (25961):   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:761)
04-12 17:02:41.650 I/art     (25961):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:98)
04-12 17:02:41.650 I/art     (25961):   at void com.google.android.gms.ads.internal.util.f.dispatchMessage(android.os.Message) (:com.google.android.gms.dynamite_dynamitemodulesa@12521023@12.5.21 (040408-189987672):9)
04-12 17:02:41.650 I/art     (25961):   at void android.os.Looper.loop() (Looper.java:156)
04-12 17:02:41.650 I/art     (25961):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6523)
04-12 17:02:41.650 I/art     (25961):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
04-12 17:02:41.650 I/art     (25961):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:942)
04-12 17:02:41.650 I/art     (25961):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:832)
04-12 17:02:41.650 I/art     (25961): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.RenderProcessGoneDetail" on path: DexPathList[[zip file "/data/app/com.android.chrome-2/base.apk"],nativeLibraryDirectories=[/data/app/com.android.chrome-2/lib/arm, /data/app/com.android.chrome-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]
04-12 17:02:41.650 I/art     (25961):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
04-12 17:02:41.650 I/art     (25961):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
04-12 17:02:41.650 I/art     (25961):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
04-12 17:02:41.650 I/art     (25961):   at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (WebViewChromium.java:42)
04-12 17:02:41.650 I/art     (25961):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:636)
04-12 17:02:41.650 I/art     (25961):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:572)
04-12 17:02:41.650 I/art     (25961):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:555)
04-12 17:02:41.650 I/art     (25961):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:542)
04-12 17:02:41.650 I/art     (25961):   at void android.webkit.WebView.<init>(android.content.Context) (WebView.java:532)
04-12 17:02:41.650 I/art     (25961):   at void com.google.android.gms.ads.internal.webview.u.<init>(com.google.android.gms.ads.internal.webview.at, com.google.android.gms.ads.internal.webview.av, java.lang.String, boolean, gh, com.google.android.gms.ads.internal.util.client.m, com.google.android.gms.ads.internal.csi.l, com.google.android.gms.ads.internal.bn, com.google.android.gms.ads.internal.w, com.google.android.gms.ads.internal.clearcut.a) (:com.google.android.gms.dynamite_dynamitemodulesa@12521023@12.5.21 (040408-189987672):1)
04-12 17:02:41.650 I/art     (25961):   at java.lang.Object com.google.android.gms.ads.internal.webview.q.call() ((null):5)
04-12 17:02:41.650 I/art     (25961):   at java.lang.Object com.google.android.gms.ads.internal.util.br.a(java.util.concurrent.Callable) (:com.google.android.gms.dynamite_dynamitemodulesa@12521023@12.5.21 (040408-189987672):23)
04-12 17:02:41.650 I/art     (25961):   at com.google.android.gms.ads.internal.webview.i com.google.android.gms.ads.internal.webview.o.a(android.content.Context, com.google.android.gms.ads.internal.webview.av, java.lang.String, boolean, boolean, gh, com.google.android.gms.ads.internal.util.client.m, com.google.android.gms.ads.internal.csi.l, com.google.android.gms.ads.internal.bn, com.google.android.gms.ads.internal.w, com.google.android.gms.ads.internal.clearcut.a) (:com.google.android.gms.dynamite_dynamitemodulesa@12521023@12.5.21 (040408-189987672):8)
04-12 17:02:41.650 I/art     (25961):   at com.google.android.gms.ads.internal.webview.i com.google.android.gms.ads.nonagon.ad.webview.a.a(com.google.android.gms.ads.internal.client.k) (:com.google.android.gms.dynamite_dynamitemodulesa@12521023@12.5.21 (040408-189987672):11)
04-12 17:02:41.650 I/art     (25961):   at com.google.android.gms.ads.internal.util.future.w com.google.android.gms.ads.nonagon.render.f.a(java.lang.Object) ((null):4)
04-12 17:02:41.650 I/art     (25961):   at void com.google.android.gms.ads.internal.util.future.j.run() ((null):3)
04-12 17:02:41.650 I/art     (25961):   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:761)
04-12 17:02:41.650 I/art     (25961):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:98)
04-12 17:02:41.650 I/art     (25961):   at void com.google.android.gms.ads.internal.util.f.dispatchMessage(android.os.Message) (:com.google.android.gms.dynamite_dynamitemodulesa@12521023@12.5.21 (040408-189987672):9)
04-12 17:02:41.650 I/art     (25961):   at void android.os.Looper.loop() (Looper.java:156)
04-12 17:02:41.650 I/art     (25961):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6523)
04-12 17:02:41.650 I/art     (25961):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
04-12 17:02:41.650 I/art     (25961):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:942)
04-12 17:02:41.650 I/art     (25961):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:832)
04-12 17:02:41.650 I/art     (25961): 
04-12 17:02:41.651 I/art     (25961): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.hb>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/SafeBrowsingResponse;
04-12 17:02:41.651 I/art     (25961):   at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (WebViewChromium.java:42)
04-12 17:02:41.651 I/art     (25961):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:636)
04-12 17:02:41.651 I/art     (25961):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:572)
04-12 17:02:41.651 I/art     (25961):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:555)
04-12 17:02:41.651 I/art     (25961):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:542)
04-12 17:02:41.651 I/art     (25961):   at void android.webkit.WebView.<init>(android.content.Context) (WebView.java:532)
04-12 17:02:41.651 I/art     (25961):   at void com.google.android.gms.ads.internal.webview.u.<init>(com.google.android.gms.ads.internal.webview.at, com.google.android.gms.ads.internal.webview.av, java.lang.String, boolean, gh, com.google.android.gms.ads.internal.util.client.m, com.google.android.gms.ads.internal.csi.l, com.google.android.gms.ads.internal.bn, com.google.android.gms.ads.internal.w, com.google.android.gms.ads.internal.clearcut.a) (:com.google.android.gms.dynamite_dynamitemodulesa@12521023@12.5.21 (040408-189987672):1)
04-12 17:02:41.651 I/art     (25961):   at java.lang.Object com.google.android.gms.ads.internal.webview.q.call() ((null):5)
04-12 17:02:41.651 I/art     (25961):   at java.lang.Object com.google.android.gms.ads.internal.util.br.a(java.util.concurrent.Callable) (:com.google.android.gms.dynamite_dynamitemodulesa@12521023@12.5.21 (040408-189987672):23)
04-12 17:02:41.651 I/art     (25961):   at com.google.android.gms.ads.internal.webview.i com.google.android.gms.ads.internal.webview.o.a(android.content.Context, com.google.android.gms.ads.internal.webview.av, java.lang.String, boolean, boolean, gh, com.google.android.gms.ads.internal.util.client.m, com.google.android.gms.ads.internal.csi.l, com.google.android.gms.ads.internal.bn, com.google.android.gms.ads.internal.w, com.google.android.gms.ads.internal.clearcut.a) (:com.google.android.gms.dynamite_dynamitemodulesa@12521023@12.5.21 (040408-189987672):8)
04-12 17:02:41.651 I/art     (25961):   at com.google.android.gms.ads.internal.webview.i com.google.android.gms.ads.nonagon.ad.webview.a.a(com.google.android.gms.ads.internal.client.k) (:com.google.android.gms.dynamite_dynamitemodulesa@12521023@12.5.21 (040408-189987672):11)
04-12 17:02:41.651 I/art     (25961):   at com.google.android.gms.ads.internal.util.future.w com.google.android.gms.ads.nonagon.render.f.a(java.lang.Object) ((null):4)
04-12 17:02:41.651 I/art     (25961):   at void com.google.android.gms.ads.internal.util.future.j.run() ((null):3)
04-12 17:02:41.651 I/art     (25961):   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:761)
04-12 17:02:41.651 I/art     (25961):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:98)
04-12 17:02:41.651 I/art     (25961):   at void com.google.android.gms.ads.internal.util.f.dispatchMessage(android.os.Message) (:com.google.android.gms.dynamite_dynamitemodulesa@12521023@12.5.21 (040408-189987672):9)
04-12 17:02:41.651 I/art     (25961):   at void android.os.Looper.loop() (Looper.java:156)
04-12 17:02:41.651 I/art     (25961):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6523)
04-12 17:02:41.651 I/art     (25961):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
04-12 17:02:41.651 I/art     (25961):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:942)
04-12 17:02:41.651 I/art     (25961):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:832)
04-12 17:02:41.651 I/art     (25961): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.SafeBrowsingResponse" on path: DexPathList[[zip file "/data/app/com.android.chrome-2/base.apk"],nativeLibraryDirectories=[/data/app/com.android.chrome-2/lib/arm, /data/app/com.android.chrome-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]
04-12 17:02:41.651 I/art     (25961):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
04-12 17:02:41.651 I/art     (25961):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
04-12 17:02:41.651 I/art     (25961):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
04-12 17:02:41.651 I/art     (25961):   at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (WebViewChromium.java:42)
04-12 17:02:41.651 I/art     (25961):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:636)
04-12 17:02:41.651 I/art     (25961):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:572)
04-12 17:02:41.651 I/art     (25961):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:555)
04-12 17:02:41.651 I/art     (25961):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:542)
04-12 17:02:41.651 I/art     (25961):   at void android.webkit.WebView.<init>(android.content.Context) (WebView.java:532)
04-12 17:02:41.651 I/art     (25961):   at void com.google.android.gms.ads.internal.webview.u.<init>(com.google.android.gms.ads.internal.webview.at, com.google.android.gms.ads.internal.webview.av, java.lang.String, boolean, gh, com.google.android.gms.ads.internal.util.client.m, com.google.android.gms.ads.internal.csi.l, com.google.android.gms.ads.internal.bn, com.google.android.gms.ads.internal.w, com.google.android.gms.ads.internal.clearcut.a) (:com.google.android.gms.dynamite_dynamitemodulesa@12521023@12.5.21 (040408-189987672):1)
04-12 17:02:41.651 I/art     (25961):   at java.lang.Object com.google.android.gms.ads.internal.webview.q.call() ((null):5)
04-12 17:02:41.651 I/art     (25961):   at java.lang.Object com.google.android.gms.ads.internal.util.br.a(java.util.concurrent.Callable) (:com.google.android.gms.dynamite_dynamitemodulesa@12521023@12.5.21 (040408-189987672):23)
04-12 17:02:41.651 I/art     (25961):   at com.google.android.gms.ads.internal.webview.i com.google.android.gms.ads.internal.webview.o.a(android.content.Context, com.google.android.gms.ads.internal.webview.av, java.lang.String, boolean, boolean, gh, com.google.android.gms.ads.internal.util.client.m, com.google.android.gms.ads.internal.csi.l, com.google.android.gms.ads.internal.bn, com.google.android.gms.ads.internal.w, com.google.android.gms.ads.internal.clearcut.a) (:com.google.android.gms.dynamite_dynamitemodulesa@12521023@12.5.21 (040408-189987672):8)
04-12 17:02:41.651 I/art     (25961):   at com.google.android.gms.ads.internal.webview.i com.google.android.gms.ads.nonagon.ad.webview.a.a(com.google.android.gms.ads.internal.client.k) (:com.google.android.gms.dynamite_dynamitemodulesa@12521023@12.5.21 (040408-189987672):11)
04-12 17:02:41.651 I/art     (25961):   at com.google.android.gms.ads.internal.util.future.w com.google.android.gms.ads.nonagon.render.f.a(java.lang.Object) ((null):4)
04-12 17:02:41.651 I/art     (25961):   at void com.google.android.gms.ads.internal.util.future.j.run() ((null):3)
04-12 17:02:41.651 I/art     (25961):   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:761)
04-12 17:02:41.651 I/art     (25961):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:98)
04-12 17:02:41.651 I/art     (25961):   at void com.google.android.gms.ads.internal.util.f.dispatchMessage(android.os.Message) (:com.google.android.gms.dynamite_dynamitemodulesa@12521023@12.5.21 (040408-189987672):9)
04-12 17:02:41.651 I/art     (25961):   at void android.os.Looper.loop() (Looper.java:156)
04-12 17:02:41.651 I/art     (25961):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6523)
04-12 17:02:41.651 I/art     (25961):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
04-12 17:02:41.651 I/art     (25961):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:942)
04-12 17:02:41.651 I/art     (25961):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:832
```

**Comment by newky2k** [comment]
@Umar3x  Could you please provide a small sample project so we can replicate this issue.  Additionally we have now release preview 2 for version of 70.1501.0 which could also resolve the issue.
