### ISSUE TITLE
build error: MediationRewardedVideoAdListenerImplementor is not abstract and does not override abstract method zzc(Bundle) 

### ISSUE THREAD

**Issue by ish-1313** [xamarin/GooglePlayServicesComponents#241]
### Xamarin.Android Version (eg: 6.0):
9.3.0.23

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10 1903 (build 18362.239)

### Google Play Services Version (eg: 8.4.0):
71.1712.0

### Describe your Issue:
after upgrade to 71.1712.0 project (xamarin.forms) build fails with

error: MediationRewardedVideoAdListenerImplementor is not abstract and does not override abstract method zzc(Bundle) in MediationRewardedVideoAdListener
public class MediationRewardedVideoAdListenerImplementor	ProjectName.Android	C:\work\ProjectName\ProjectName\ProjectName.Android\obj\Debug\90\android\src\mono\com\google\android\gms\ads\reward\mediation\MediationRewardedVideoAdListenerImplementor.java	4	

downgrading to 60.1142.1 resolves this issue

Microsoft Visual Studio Professional 2019
Version 16.1.6
VisualStudio.16.Release/16.1.6+29102.190
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

Mono Debugging for Visual Studio   16.1.1 (2473f22)
Support for debugging Mono processes with Visual Studio.

Xamarin   16.1.0.545 (d16-1@db7c858e8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.1.0.418 (remotes/origin/d16-1@5b958bb10)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.2.112 (4db4af4)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.3.0.23 (HEAD/d0b48056f)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2018-08@3a07bd426d3
    Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
    LibZipSharp: grendello/LibZipSharp/d16-1@44de300
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26

**Comment by moljac** [comment]
Is this `Xamarin.GooglePlayServices.Ads.Lite` nuget package?

Did you try patch for it? `71.1712.1`

https://www.nuget.org/packages/Xamarin.GooglePlayServices.Ads.Lite/71.1712.1

**Comment by moljac** [comment]
Related/Duplicate: https://github.com/xamarin/GooglePlayServicesComponents/issues/236

Closing this one.

**Comment by ish-1313** [comment]
> 
> 
> Is this `Xamarin.GooglePlayServices.Ads.Lite` nuget package?
> 
> Did you try patch for it? `71.1712.1`
> 
> https://www.nuget.org/packages/Xamarin.GooglePlayServices.Ads.Lite/71.1712.1
No, I am not using Lite

**Comment by Redth** [comment]
Ads depends on Ads Lite. You will need to add an explicit nuget package reference to Ads Lite 71.1712.1.

**Comment by ish-1313** [comment]
thank you. will try
