### ISSUE TITLE
FirebaseVisionBarcodeDetector missing in v124.0.0 (again)

### ISSUE THREAD

**Issue by subsembly** [xamarin/GooglePlayServicesComponents#388]
I am getting a FirebaseVisionBarcodeDetector via FirebaseVision.Instance.GetVisionBarcodeDetector(). However, after upgrading from 71.1700.4 to 124.0.0, neither GetVisionBarcodeDetector nor the class FirebaseVisionBarcodeDetector is bound anymore. Hence it neither compiles nor can be used in any other way.

**Comment by moljac** [comment]
Obfuscated class `zzrc` caused that:

```
    <class abstract="false" deprecated="not deprecated" extends="com.google.android.gms.internal.firebase_ml.zzrc" extends-generic-aware="com.google.android.gms.internal.firebase_ml.zzrc&lt;java.util.List&lt;com.google.firebase.ml.vision.barcode.FirebaseVisionBarcode&gt;&gt;" jni-extends="Lcom/google/android/gms/internal/firebase_ml/zzrc;" final="false" name="FirebaseVisionBarcodeDetector" static="false" visibility="public" jni-signature="Lcom/google/firebase/ml/vision/barcode/FirebaseVisionBarcodeDetector;">
```

**Comment by moljac** [comment]
After surfacing `zzrc`

```
		static Delegate cb_getVisionBarcodeDetector;
#pragma warning disable 0169
		static Delegate GetGetVisionBarcodeDetectorHandler ()
		{
			if (cb_getVisionBarcodeDetector == null)
				cb_getVisionBarcodeDetector = JNINativeWrapper.CreateDelegate ((_JniMarshal_PP_L) n_GetVisionBarcodeDetector);
			return cb_getVisionBarcodeDetector;
		}

		static IntPtr n_GetVisionBarcodeDetector (IntPtr jnienv, IntPtr native__this)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Firebase.ML.Vision.FirebaseVision> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			return JNIEnv.ToLocalJniHandle (__this.VisionBarcodeDetector);
		}
#pragma warning restore 0169

		public virtual unsafe global::Firebase.ML.Vision.Barcode.FirebaseVisionBarcodeDetector VisionBarcodeDetector {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.google.firebase.ml.vision']/class[@name='FirebaseVision']/method[@name='getVisionBarcodeDetector' and count(parameter)=0]"
			[Register ("getVisionBarcodeDetector", "()Lcom/google/firebase/ml/vision/barcode/FirebaseVisionBarcodeDetector;", "GetGetVisionBarcodeDetectorHandler")]
			get {
				const string __id = "getVisionBarcodeDetector.()Lcom/google/firebase/ml/vision/barcode/FirebaseVisionBarcodeDetector;";
				try {
					var __rm = _members.InstanceMethods.InvokeVirtualObjectMethod (__id, this, null);
					return global::Java.Lang.Object.GetObject<global::Firebase.ML.Vision.Barcode.FirebaseVisionBarcodeDetector> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
				} finally {
				}
			}
		}

```

**Comment by moljac** [comment]
fixed in:

https://github.com/xamarin/GooglePlayServicesComponents/commit/61f03338b92ced48821155d4f4786866eebdecf9

tagged

https://github.com/xamarin/GooglePlayServicesComponents/releases/tag/100.20201015-issue-388-Firebase.Vision

**Comment by moljac** [comment]
Please try 

https://www.nuget.org/packages/Xamarin.Firebase.ML.Vision/124.0.0.1

and report results here.

Even better if the issue is fixed please close the issue.

**Comment by subsembly** [comment]
Thanks for the quick response, but, sorry, after updating to v124.0.1, it still produces the very same compilation errors:

error CS0246: The type or namespace name 'FirebaseVisionBarcodeDetector' could not be found (are you missing a using directive or an assembly reference?)
error CS1061: 'FirebaseVision' does not contain a definition for 'GetVisionBarcodeDetector' and no accessible extension method 'GetVisionBarcodeDetector' accepting a first argument of type 'FirebaseVision' could be found (are you missing a using directive or an assembly reference?)

I even deleted all bin/obj files and did a complete recompile to be sure.

**Comment by moljac** [comment]
repro sample please.

Please be sure that R8 is not removing classes/methods. 

Try adding proguard config file.... If not give me repro sample minimal, so I can bust some proguard.cfg

**Comment by ccitl** [comment]
I can confirm the same that the FirebaseVisionBarcodeDetector doesn't appear in v124.0.1 but does appear in v124.0.0.1.
Unfortunately that still means you cant use Xamarin.Firebase.ML.Vision.BarCode.Model as it seems to be incompatible with 124.0.0.1 (throws NoSuchField errors at runtime).

**Comment by moljac** [comment]
Obfuscated base classname (type) changed in the version 24.0.1.

**Comment by moljac** [comment]
@subsembly @ccitl 

Please try

https://www.nuget.org/packages/Xamarin.Firebase.ML.Vision/124.0.1.1

and report results here.

Thanks

**Comment by moljac** [comment]
NOTE: 24.0.3

`FirebaseVisionBarcodeDetector` is missing AGAIN. Obfuscated base class has changed again and class was not surfaced.

This will happen in the future (most likely).

**Comment by ccitl** [comment]
Can confirm that the issue was resolved in 124.0.1.1

**Comment by moljac** [comment]
It will happen again (most likely), because there is no guarantee that obfuscated classes will not change typename.

Closing this one!

Thanks
